### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by v-yuyao** [v-yuyao/LintCode-LeetCode-Practice#2]
- [ ] Change project name 

- [ ] Improve project structure

- [ ] Update README.md

- [ ] Prettify UI

- [ ] Add index page

- [ ] Keep updating problems under all topics
